In [1]:
import pandas as pd
import spacy
import csv
nlp = spacy.load("en_core_web_sm")
from tqdm import tqdm
tqdm.pandas()

In [2]:
path = "/Users/ivowings/Sync/Thesis/Datasources/Skills/soft_skills_fromsoftskillmatching.csv"
path2 = "/Users/ivowings/Sync/Thesis/Datasources/Skills/soft_skills_fromsoftskillmatching(2).csv"

In [3]:
import csv
with open(path, newline='', encoding = 'utf8') as f:
    csvread = csv.reader(f)
    batch_data = list(csvread)

with open(path2, newline='', encoding = 'utf8') as f:
    csvread = csv.reader(f)
    batch_data2 = list(csvread)

In [4]:
df1 = pd.DataFrame(batch_data, columns=['is_soft_skill', 'soft_skill', 'context', 'test'])
df1['test'] = df1['test'].fillna('')
df1['context'] = df1['context'] + ' ' + df1['test']
df1 = df1[['is_soft_skill', 'soft_skill', 'context']]
df1 = df1.drop(index=0)

In [5]:
df2 = pd.DataFrame(batch_data2, columns=['is_soft_skill', 'soft_skill', 'context'])
df2 = df2.drop(index=0)

In [6]:
df = pd.concat([df1,df2]).reset_index()
df

,index,is_soft_skill,soft_skill,context
0,1,0,dynamic,be look for a temporary opportunity within a p...
1,2,1,team customer interaction,effective member of the operation leadership x...
2,3,1,systematic,linux shell be able to demonstrate a xxx and a...
3,4,1,autonomy,territory manager role offer significant respo...
4,5,1,hard working sales person,"you must be an enthuse , passionate , xxx xxx ..."
...,...,...,...,...
7406,3701,1,ability to compile a report,strong understand of legislation best practice...
7407,3702,0,dynamic,"to provide fix report , interactive report bui..."
7408,3703,1,political awareness,conduct and respect posse cultural and xxx xxx...
7409,3704,1,leadership skills,high level of experience and xxx xxx be essent...
7410,3705,0,team working,you will be work within a xxx xxx closely with...

In [7]:
def character_counter(text):
    from collections import Counter
    my_str = text
    counter = Counter(my_str)
    return counter['*']

In [8]:
df['test'] = df['context'].str.replace(r'[^A-Za-z0-9 ]+', ' ')
df['test'] = df['test'].str.replace(r'xxx ', 'XXX', regex=True)
df['test'] = df['test'].str.replace(r'xxx', 'XXX', regex=True)
df['test'] = df['test'].str.replace(r'(X+)', '* ', regex=True)
df['test'] = df['test'].str.strip()
df['test'] = df['test'].str.lower()
df['test'] = df['test'].str.replace(r'[ ]{2,}', ' ', regex=True)

df['test2'] = df['test'].apply(character_counter)
df

#Removing rows which have multiple soft skills 
df = df[df.test2==1]

<ipython-input-8-b60d985b1d84>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['test'] = df['context'].str.replace(r'[^A-Za-z0-9 ]+', ' ')

In [9]:
test = df['test'].str.split('*',expand=True)
df = df.join(test)
df

,index,is_soft_skill,soft_skill,context,test,test2,0,1
0,1,0,dynamic,be look for a temporary opportunity within a p...,be look for a temporary opportunity within a p...,1,be look for a temporary opportunity within a p...,environment please forward your cv today
1,2,1,team customer interaction,effective member of the operation leadership x...,effective member of the operation leadership *...,1,effective member of the operation leadership,to develop positive relationship a
2,3,1,systematic,linux shell be able to demonstrate a xxx and a...,linux shell be able to demonstrate a * and ana...,1,linux shell be able to demonstrate a,and analytical approach to
3,4,1,autonomy,territory manager role offer significant respo...,territory manager role offer significant respo...,1,territory manager role offer significant respo...,
4,5,1,hard working sales person,"you must be an enthuse , passionate , xxx xxx ...",you must be an enthuse passionate * with a fle...,1,you must be an enthuse passionate,with a flexible attitude
...,...,...,...,...,...,...,...,...
7406,3701,1,ability to compile a report,strong understand of legislation best practice...,strong understand of legislation best practice...,1,strong understand of legislation best practice,provide a clinical opinion
7407,3702,0,dynamic,"to provide fix report , interactive report bui...",to provide fix report interactive report build...,1,to provide fix report interactive report build...,legal document creation
7408,3703,1,political awareness,conduct and respect posse cultural and xxx xxx...,conduct and respect posse cultural and * and s...,1,conduct and respect posse cultural and,and sensitivity exercise flexiblity
7409,3704,1,leadership skills,high level of experience and xxx xxx be essent...,high level of experience and * be essential a ...,1,high level of experience and,be essential a well
7410,3705,0,team working,you will be work within a xxx xxx closely with...,you will be work within a * closely with the f...,1,you will be work within a,closely with the family who play a very active

In [10]:
testdf = df[[0,'soft_skill',1, 'is_soft_skill']]
testdf = testdf.rename(columns={0:'left_context', 1:'right_context'})

testdf = testdf.rename(columns={'soft_skill' : 'candidate_skill', 'is_soft_skill':'label'})
testdf

,left_context,candidate_skill,right_context,label
0,be look for a temporary opportunity within a p...,dynamic,environment please forward your cv today,0
1,effective member of the operation leadership,team customer interaction,to develop positive relationship a,1
2,linux shell be able to demonstrate a,systematic,and analytical approach to,1
3,territory manager role offer significant respo...,autonomy,,1
4,you must be an enthuse passionate,hard working sales person,with a flexible attitude,1
...,...,...,...,...
7406,strong understand of legislation best practice,ability to compile a report,provide a clinical opinion,1
7407,to provide fix report interactive report build...,dynamic,legal document creation,0
7408,conduct and respect posse cultural and,political awareness,and sensitivity exercise flexiblity,1
7409,high level of experience and,leadership skills,be essential a well,1
7410,you will be work within a,team working,closely with the family who play a very active,0

In [11]:
#Removing candidate skills with more than 4 tokens in order to standardize the data with the manually labeled data

testdf['length'] = testdf['candidate_skill'].apply(nlp)
testdf['length'] = testdf['length'].apply(len)
testdf = testdf[testdf.length<=4]
testdf

,left_context,candidate_skill,right_context,label,length
0,be look for a temporary opportunity within a p...,dynamic,environment please forward your cv today,0,1
1,effective member of the operation leadership,team customer interaction,to develop positive relationship a,1,3
2,linux shell be able to demonstrate a,systematic,and analytical approach to,1,1
3,territory manager role offer significant respo...,autonomy,,1,1
4,you must be an enthuse passionate,hard working sales person,with a flexible attitude,1,4
...,...,...,...,...,...
7405,a fun and,dynamic,opportunity that offer fantastic career progr...,0,1
7407,to provide fix report interactive report build...,dynamic,legal document creation,0,1
7408,conduct and respect posse cultural and,political awareness,and sensitivity exercise flexiblity,1,2
7409,high level of experience and,leadership skills,be essential a well,1,2
7410,you will be work within a,team working,closely with the family who play a very active,0,2

In [12]:
testdf.to_csv("/Users/ivowings/Sync/Thesis/Datasources/Skills/Pre annotated soft skills/annotated_soft_skills_context.csv",
         quoting=csv.QUOTE_NONNUMERIC,
                index=False)